[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F429ZITx"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=--gc-sections",
  "-C", "link-arg=--build-id=none"
]
